Infrastructure as Code. Terraform
Durf1985/devops_study_infra pull request #12
Opened 2022-09-21 22:31 UTC by Durf1985

Added working main.tf template based on image "reddit-base" to create VM instance with ssh access

* ssh access is not working: Permission denied

# Completed homework №

- [ ] The main homework
- [ ] Task with *

## In the process done:

- Item 1
- Item 2

## How to launch a project:

- For example, run the X command in the Y directory

## How to check the performance:

- For example, follow the link <http://localhost:8080>

## PR checklist

- [ ] The label with the homework number
- [ ] The label with a homework topic

2022-09-22 09:21 UTC, Durf1985 commented
![photo_2022-09-22_16-20-37](https://user-images.githubusercontent.com/36097814/191709554-cab5adb7-89ec-4568-b7af-dfbbea6fbd79.jpg)
![photo_2022-09-22_16-20-52](https://user-images.githubusercontent.com/36097814/191709562-f269d431-df6b-4b54-a0f8-2620498d12e7.jpg)

2022-09-22 09:51 UTC, loktionovam requested changes

2022-09-22 09:51 UTC, loktionovam commented on .gitignore
> +.terraform/
add `.terraform.lock.hcl` also

2022-09-22 09:51 UTC, loktionovam commented on terraform/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
remove this file because it auto generated by `terraform init` command and is not a part of your source code

2022-09-23 09:19 UTC, loktionovam commented on terraform/outputs.tf
> +  value = google_compute_instance.app.network_interface.0.access_config.0.nat_ip
Add the description of this output

https://cloud.google.com/docs/terraform/best-practices-for-terraform#outputs

2022-09-23 09:19 UTC, loktionovam commented on terraform/main.tf
> +    ssh-keys = "appuser:${file("~/github_repo/devops_study_infra/packer/scripts/TXT.pub")}"
This absolute path can be different on different computer (for example my path will be `~/src/github/bla-bla`) so replace it by relative path

2022-10-06 08:08 UTC, loktionovam requested changes

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +    source_image = "projects/clgcporg2-118/global/images/reddit-full-1664802177"
here you should use your project variable rather than hardcoding

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +    subnetwork = "regions/us-central1/subnetworks/default"
use region variable there rather than hardcoding

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_instance_template" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_instance_group_manager" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_firewall" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_global_address" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_health_check" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_backend_service" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_url_map" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_target_http_proxy" "default" {
replace `default` resource name by something more suitable

2022-10-06 08:08 UTC, loktionovam commented on terraform/lb.tf
> +resource "google_compute_global_forwarding_rule" "default" {
replace `default` resource name by something more suitable

2022-10-10 09:59 UTC, loktionovam requested changes
You need to add `terraform/terraform.tfvars.example` because your tests are broken
https://github.com/Durf1985/devops_study_infra/commit/2c26adedd81d4403165630596bf54f05f6b2315d/checks

2022-10-10 13:42 UTC, loktionovam approved these changes

2022-10-10 13:43 UTC, merged