Working with roles and environments
Durf1985/devops_study_infra pull request #17
Opened 2022-12-08 04:40 UTC by Durf1985

Instead of app.yml/db.yml playbooks, created roles that using split files into functional chunks

# Completed homework №

- [ ] The main homework
- [ ] Task with *

## In the process done:

- Item 1
- Item 2

## How to launch a project:

- For example, run the X command in the Y directory

## How to check the performance:

- For example, follow the link <http://localhost:8080>

## PR checklist

- [ ] The label with the homework number
- [ ] The label with a homework topic

2022-12-13 05:26 UTC, loktionovam requested changes

2022-12-13 05:26 UTC, loktionovam commented on ansible/roles/app/tasks/main.yml
> +    src: templates/db_config.j2
Here you can use `db_config.j2` without `template` directory prefix (like you do when template `src: mongod.conf.j2` )

2022-12-13 05:26 UTC, loktionovam commented on ansible/environments/prod/group_vars/app
> +default:
Here is a problem with indentation

2022-12-14 06:04 UTC, loktionovam requested changes

2022-12-14 06:04 UTC, loktionovam commented on ansible/ansible.cfg
> +vault_password_file = ./vault.key
It is better to store vault key completely outside of your repo, for example in `~/.ansible/vault.key`. This prevents accidentally commit of your key.

2022-12-14 06:10 UTC, Durf1985 commented on ansible/ansible.cfg
> +vault_password_file = ./vault.key
fix

2022-12-14 06:29 UTC, loktionovam approved these changes

2022-12-14 06:29 UTC, merged