Development and testing of Ansible roles and playbooks
Durf1985/devops_study_infra pull request #18
Opened 2022-12-16 03:02 UTC by Durf1985

Creating local test infrastracture for playbooks and roles

## In the process done:

* Local development using Vagrant, refinement of roles for provisioning in Vagrant
 * Role testing using Molecule and Testinfra
 * Switching image collection by packer to using roles
 

## How to setup the project:
* In directory ~/your_repo/ansible/ execute following command:
```bash
`vagrant up`
```
after that create molecule testing infrastracture
```bash
molecule init scenario -r your_role_name -d vagrant your_scenario_name
```
add additional tests if it necessary, and configure the converge.yml and molecule.yml in created directory 

## How to check the project:

* In directory ~/your_repo/ansible/roles/your_role_directory execute following command:
```bash
molecule test
```

## PR checklist

The label with the homework number, in label description - homework lecture and topic

2022-12-19 05:45 UTC, loktionovam requested changes

2022-12-19 05:45 UTC, loktionovam commented on ansible/playbooks/users.yml
> +    - name: Debug
This is unnecessary and should be deleted

2022-12-26 12:09 UTC, loktionovam requested changes
Update README.md accordingly your changes

2022-12-26 12:09 UTC, loktionovam commented on ansible/roles/db/molecule/default/INSTALL.rst
> +    $ pip install 'molecule_vagrant'
It is better to move this to requirements.txt file and pin the version.

2022-12-26 12:09 UTC, loktionovam commented on ansible/roles/db/molecule/default/molecule.yml
> +lint: yamllint
I've got the error:

```bash
╰─❯ molecule test                                                                                                                                                                                       ─╯
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun with role_name_check=0...
INFO     Set ANSIBLE_LIBRARY=/home/isaak/.cache/ansible-compat/7bdc25/modules:/home/isaak/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/home/isaak/.cache/ansible-compat/7bdc25/collections:/home/isaak/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/home/isaak/.cache/ansible-compat/7bdc25/roles:/home/isaak/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
CRITICAL Deprecated linter config found, migrate to v3 schema. See https://github.com/ansible-community/molecule/issues/2293
```

Migrate your linter configuration or repin your packages in requirements.txt with appropriate version. The first is preferably

2022-12-26 12:09 UTC, loktionovam commented on ansible/Vagrantfile
> +        ansible.extra_vars = "/home/fallgeratoor/github_repo/devops_study_infra/ansible/environments/dev/group_vars/tag_reddit-app.yml"
Do not use absolute paths because this code is not reusable and portable

2022-12-26 12:09 UTC, loktionovam commented on ansible/ansible.cfg
> +deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian <mydist> contrib
What does this string mean?

2022-12-26 12:09 UTC, loktionovam commented on ansible/playbooks/site.yml
> +# - ansible.builtin.import_playbook: users.yml
If you want to remove your code it is better to remove it rather than comment because you can accidentally uncomment this and get an error

2022-12-26 12:09 UTC, loktionovam commented on ansible/roles/db/molecule/default/tests/test_default.py
> +# check if MongoDB is enabled and running
It is better to not write "obvious" comments (as the rule: add comments only where they are strictly necessary)

2022-12-26 20:33 UTC, Durf1985 commented on ansible/roles/db/molecule/default/INSTALL.rst
> +    $ pip install 'molecule_vagrant'
I move molecule_vagrant to requiremnts.txt, but I did not touch this file, i.e. delete it, or just clear it, or some other option

2023-01-04 05:22 UTC, loktionovam approved these changes

2023-01-04 05:22 UTC, loktionovam commented on README.md
> +echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
It is better to use `$(lsb_release -cs)` rather than hardcode `bionic`

2023-01-04 05:22 UTC, loktionovam commented on README.md
> +* In directory `environments` contains files and folders responsible for various environments, which contain their own variables and settings, as well as a dynamic inventory script. Your roles will t
`contains files and folders responsible` -> `place files and folders responsible`

2023-01-04 05:22 UTC, loktionovam commented on README.md
> +* To check your dinamic inventory execute in directory `~/your_repo/ansible` next command
`dinamic` -> `dynamic`

2023-01-04 05:22 UTC, loktionovam commented on README.md
> +* Roles have next sturcture
`next` -> `the following`

2023-01-04 05:22 UTC, loktionovam commented on README.md
> +* To launch playbooks, run the following command in the direcotry `~/your_repo/ansible`
`launch playbooks` -> `run playbooks`, `direcotry` -> `directory`

2023-01-04 15:39 UTC, merged